### ISSUE TITLE
Configurable TS pins

### ISSUE THREAD

**Issue by Jatsekku** [RobertoBenjami/stm32_graphics_display_drivers#20]
Hi, great job!
I recommend to pull out TS pins configuration to header file. 
Not all LCD has XP/XM/YP/YM on data pins pre-configurated like it is done inside lib.
It's small change but very helpfull ;)

**Comment by RobertoBenjami** [comment]
The lcdts_io_gpio8 driver is specially designed for displays that can be plugged into the arduino. I put the touch in the driver because lcd and touch are on common pins, so its program is inseparable. If the touch pins are completely independent, the program can also be separated and there is no need to switch the function of the pins. In this case, you may want to use lcd_io_gpio8 and copy the touch program to another ts_io program from lcdts_io_gpio8.
